import 'package:employees_app/utils/date_extention.dart';
import 'package:objectbox/objectbox.dart';

@Entity()
class Employee {
  /// Employee Id Auto generated by Objectbox
  @Id()
  int id; 

  /// Employee name
  String name;

  /// Employee role like Software engineer, developer etc
  String role;

  /// Joinging date of employee
  DateTime startDate;

  /// Relieving date of employee
  DateTime? endDate;

  /// This status used for soft delete
  bool isDeleted;

  Employee({this.id = 0, required this.name, required this.role, required this.startDate,  this.endDate, this.isDeleted = false});

  /// To verify the employee relived from organisation
  bool isOldEmplyee(){
    return !(endDate == null || endDate!.isAfter(DateTime.now()));
  }

  /// Date descrtion display in employee card
  String getDateDescription(){
    if(isOldEmplyee()) return '${startDate.convertAppFromatDate()} - ${endDate?.convertAppFromatDate()}';
    return 'From ${startDate.convertAppFromatDate()}';
  }

}