// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/employee.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 4798898986939659143),
      name: 'Employee',
      lastPropertyId: const IdUid(6, 3805830667760608126),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2290481533106231736),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2989041680840171892),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 229756391724971431),
            name: 'role',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4583904768474971168),
            name: 'startDate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 675990178834411031),
            name: 'endDate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3805830667760608126),
            name: 'isDeleted',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 4798898986939659143),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Employee: EntityDefinition<Employee>(
        model: _entities[0],
        toOneRelations: (Employee object) => [],
        toManyRelations: (Employee object) => {},
        getId: (Employee object) => object.id,
        setId: (Employee object, int id) {
          object.id = id;
        },
        objectToFB: (Employee object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final roleOffset = fbb.writeString(object.role);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, roleOffset);
          fbb.addInt64(3, object.startDate.millisecondsSinceEpoch);
          fbb.addInt64(4, object.endDate?.millisecondsSinceEpoch);
          fbb.addBool(5, object.isDeleted);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final endDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final roleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final startDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final endDateParam = endDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endDateValue);
          final isDeletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final object = Employee(
              id: idParam,
              name: nameParam,
              role: roleParam,
              startDate: startDateParam,
              endDate: endDateParam,
              isDeleted: isDeletedParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Employee] entity fields to define ObjectBox queries.
class Employee_ {
  /// see [Employee.id]
  static final id = QueryIntegerProperty<Employee>(_entities[0].properties[0]);

  /// see [Employee.name]
  static final name = QueryStringProperty<Employee>(_entities[0].properties[1]);

  /// see [Employee.role]
  static final role = QueryStringProperty<Employee>(_entities[0].properties[2]);

  /// see [Employee.startDate]
  static final startDate =
      QueryIntegerProperty<Employee>(_entities[0].properties[3]);

  /// see [Employee.endDate]
  static final endDate =
      QueryIntegerProperty<Employee>(_entities[0].properties[4]);

  /// see [Employee.isDeleted]
  static final isDeleted =
      QueryBooleanProperty<Employee>(_entities[0].properties[5]);
}
